# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

#google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: '流水帳', path: 'menu', url: 'writing.html'}
- {name: '消肿', path: 'menu', url: 'xiaozhong.html'}
# - {name: 'Tech', path: 'menu', url: 'techynotes.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/youngsonger'}
- {icon: 'instagram', link: 'https://www.instagram.com/ygggg_at_ins/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yang-song-12678438/'}
- {icon: 'envelope', link: 'mailto:youngsonger@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share, but please indicate that it is from Yang@git!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
